### ISSUE TITLE
version numbers should match Electron's

### ISSUE THREAD

**Issue by ckerr** [electron/typescript-definitions#103]
Expected:

When wanting to pin electron's 2-0-x branch to a specific version of electron-typescript-definitions, we should do something like `"electron-typescript-definitions: ^2.0.0"` in `package.json`

Actual:

Instead [we pin to 1.3.2](https://github.com/electron/electron/pull/12940/files) which has no intuitive connection to Electron 2.0.0:
"electron-typescript-definitions": "1.3.2"`

**Comment by zeke** [comment]
> this module is currently following semver which would be very hard to enforce if we had to keep version numbers aligned.

I agree.

**Comment by MarshallOfSound** [comment]
Closing out as per the discussion above with
