### ISSUE TITLE
dialog: window is optional in docs but not in typings

### ISSUE THREAD

**Issue by bpasero** [electron/typescript-definitions#138]
E.g. https://github.com/electron/electron/blob/3-0-x/docs/api/dialog.md#dialogshowsavedialogbrowserwindow-options-callback indicates that the browser window is optional but it is not in the `electron.d.ts`

**Comment by MarshallOfSound** [comment]
It's not marked as optional but it is overloaded so their is a declaration without the window parameter.  I just checked 4.1 and 3.1 and the definitions are correct their.

What error are you seeing?

**Comment by bpasero** [comment]
@MarshallOfSound when I pass in `undefined` as first argument I get a stack trace immediately about converting some parameters within Electron.

**Comment by bpasero** [comment]
Oh I take it back, seeing the declaration now!
