### ISSUE TITLE
Property 'getURL' does not exist on type 'BrowserWindow'

### ISSUE THREAD

**Issue by Paxa** [electron/typescript-definitions#141]
Code works but typescript doesn't know about that method

```js
var template = [
  {
    label: 'Close Tab',
    click: (item, focusedWindow) => {
      console.log(focusedWindow, focusedWindow.getURL());
    },
  }
]
```

**Comment by MarshallOfSound** [comment]
@Paxa `getURL` on the `BrowserWindow` class is not documented as API and could therefore be removed at any time.  You should be using `focusedWindow.webContents.getURL()`

**Comment by Paxa** [comment]
Thanks!
