### ISSUE TITLE
DesktopCapturer.getSources doesnt return an array of DesktopCapturerSource 

### ISSUE THREAD

**Issue by renarsvilnis** [electron/typescript-definitions#145]
Noticed while trying to run the example code of `DesktopCapturer` module that the return value of `.getSources()` for a promise based return is incorrect.

As [docs](https://electronjs.org/docs/api/desktop-capturer#desktopcapturergetsourcesoptions) state it should return `Promise<DesktopCapturerSource[]>` instead of current `Promise<DesktopCapturerSource>`

**Current**

```typescript
interface DesktopCapturer extends EventEmitter {
    getSources(options: SourcesOptions, callback: (error: Error, sources: DesktopCapturerSource[]) => void): void;
    getSources(options: SourcesOptions): Promise<DesktopCapturerSource>;
  }
```

**Fixed**

```typescript
interface DesktopCapturer extends EventEmitter {
    getSources(options: SourcesOptions, callback: (error: Error, sources: DesktopCapturerSource[]) => void): void;
    getSources(options: SourcesOptions): Promise<DesktopCapturerSource[]>;
  }
```

**Comment by MarshallOfSound** [comment]
This is fixed on `master` and will be in the first `electron@7` release 👍 (it is already fixed in the nightlies)
