### ISSUE TITLE
MessageBoxOptions icon should accept string

### ISSUE THREAD

**Issue by jpmn** [electron/typescript-definitions#154]
For `MessageBoxOptions`, both the documentation and the typings in `electron.d.ts` mentions that the `icon` property only supports `NativeImage`, but the `nativeImage` documentation says (https://electronjs.org/docs/api/native-image#nativeimage):

```
In Electron, for the APIs that take images, you can pass either file paths or NativeImage
```

In `BrowserWindowConstructorOptions`: `icon?: (NativeImage) | (string);`
In `MessageBoxOptions`: `icon?: NativeImage;`

Maybe they should be the same. 

If my understanding is correct, I should have opened an issue in https://github.com/electron/electron instead as this project reads electron's documentation to generate the `electron.d.ts` file.

EDIT: I opened a PR: https://github.com/electron/electron/pull/19782

**Comment by MarshallOfSound** [comment]
Thanks for the PR @jpmn 

Looks like that PR has landed and is on it's way to all release branches 👍
