### ISSUE TITLE
File interface conflicts with lib.dom.ts

### ISSUE THREAD

**Issue by johnryan** [electron/typescript-definitions#158]
I'm seeing a conflict with another library that extends the `lib.dom.ts` File like:

```
export interface FileWithPath extends File {
    readonly path?: string;
}
```

In my case this causes a conflict with the electron `File`:

```
interface File {
 /**
  * The real path to the file on the users filesystem
  */
  path: string;
}
```

creating this error:
```
node_modules/file-selector/dist/file.d.ts:3:18 - error TS2430: Interface 'FileWithPath' incorrectly extends interface 'File'.
  Types of property 'path' are incompatible.
    Type 'string | undefined' is not assignable to type 'string'.
      Type 'undefined' is not assignable to type 'string'.

export interface FileWithPath extends File {
```

Should this definition be namespaced so that it doesn't conflict with the browser File definition?

**Comment by MarshallOfSound** [comment]
> Should this definition be namespaced so that it doesn't conflict with the browser File definition?

No, the entire purpose of this declaration is to extend the browser `File` definition because that is what Electron is doing under-the-hood in Chromium
