### ISSUE TITLE
Electron projects don't compile without DOM library

### ISSUE THREAD

**Issue by LuminescentMoon** [electron/typescript-definitions#160]
Electron + TypeScript projects don't compile without the DOM library enabled in the TypeScript compiler options. This is problematic when separate TypeScript projects are used for the main process, the renderer process, and/or the preload script to keep the globals clean.

One solution is to mock the parts of the DOM library that Electron's type definitions use. An example of this is [React's type definitions](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react/global.d.ts).

**Comment by lgrahl** [comment]
:+1: Underrated issue.

**Comment by MarshallOfSound** [comment]
This doesn't appear to be the case anymore 🤷
