### ISSUE TITLE
electron.app and electron.remote can be undefined

### ISSUE THREAD

**Issue by Timmmm** [electron/typescript-definitions#165]
Currently `electron.app` and `electron.remote` can never be `undefined` according to `electron.d.ts`, but that is wrong - they can be `undefined` depending on which process you are in.

**Comment by MarshallOfSound** [comment]
There is no way in typescript to do per-process typings.  Typescript has no concept of electron processes or API availability.  If we make them optional everywhere that would suck beyond belief

**Comment by Timmmm** [comment]
Yeah it would really suck for the types to be correct. 🤦‍♂

A better argument is that it would break a lot of code.
