### ISSUE TITLE
should getFocusedWebContents() have return type 'WebContents | null'?

### ISSUE THREAD

**Issue by kevinushey** [electron/typescript-definitions#202]
My `electron.d.ts` (from version 17.1.0) has:

```
    /**
     * The web contents that is focused in this application, otherwise returns `null`.
     */
    static getFocusedWebContents(): WebContents;
```

IIUC, because this function can return `null`, the return value should be declared as `WebContents | null`. Or am I misunderstanding something?

**Comment by erickzhao** [comment]
I think you're right. This should be fixed in the documentation itself over in the main Electron repo. :)

**Comment by kevinushey** [comment]
Thanks! It wasn't quite clear to me where and how `electron.d.ts` is generated, so I filed the issue here first -- should I close this and re-open at https://github.com/electron/electron/issues?

**Comment by erickzhao** [comment]
Feel free to make a documentation PR directly. It should look something like this:

```diff
- Returns `WebContents` - The web contents that is focused in this application, otherwise
+ Returns `WebContents` | null - The web contents that is focused in this application, otherwise
returns `null`.
```

**Comment by kevinushey** [comment]
Thank you :-) I'll do that!
