### ISSUE TITLE
Extending interfaces

### ISSUE THREAD

**Issue by mook-as** [electron/typescript-definitions#204]
Hi there!

Just wanted to check if you know of a way to extend the interfaces defined here; in my case, I want to extend `IpcMain.on` / etc. to get type checking for the event parameters.  Before b4d9d133cccd0f712d681217703195769ea7a639, it was possible to just do:
```ts
declare module "electron" {
  interface IpcMain {
    on(channel: 'foo', listener: (event: Electron.IpcMainEvent, arg1: string, …);
    … more definitions here
```
However, now the export is a type alias, so it's [not possible](https://www.typescriptlang.org/docs/handbook/2/everyday-types.html#differences-between-type-aliases-and-interfaces) to merge interfaces anymore.

This is less a bug report, and more a call to see if other people have done similar things and have a solution.

Thanks!

**Comment by Tundon** [comment]
I'm facing the same issue. Before v13, type augmentation was still possible. With the new changes, it is just not possible anymore, which is very frustrating.

So my workaround was actually modify the installed `electron.d.ts` and add something like
```ts
declare module 'electron/types' {
  export = Electron
}
```
And when I do type augmentation/merging, I would specifically 
```ts
declare module "electron/types" {
  interface MenuItemConstructorOptions {
    extraStuff?: string;
  }
}
```

This is really ugly, and I have to add a script to apply that 3 lines patch after `npm install`.

**Comment by MarshallOfSound** [comment]
It definitely still appears to be possible.  My test bed was a developer environment so it might not exactly match what folks installing production things would get.

```typescript
/// <reference path="../../../electron.d.ts" />

declare namespace Electron {
  interface IpcMain {
    on(channel: 'foo', listener: (event: Electron.IpcMainEvent, arg1: string) => void): this;
  }
}
```

Correctly augments the `ipcMain` object such that this code is type checked:
<img width="787" alt="image" src="https://user-images.githubusercontent.com/6634592/216290185-5b617584-4c29-4903-b74c-6fa08df954e1.png">
