### ISSUE TITLE
Event listener function arguments should not be optional

### ISSUE THREAD

**Issue by miniak** [electron/typescript-definitions#24]
Example

```
class WebContents extends EventEmitter {
    ...
    on(event: 'crashed', listener: (event?: Event,
                                    killed?: boolean) => void): this;
    ...
}
```

should be

```
class WebContents extends EventEmitter {
    ...
    on(event: 'crashed', listener: (event: Event,
                                    killed: boolean) => void): this;
    ...
}
```

TypeScript allows passing functions with less arguments:

```
mainWindow.webContents.on('crashed', () => console.log('crashed'));
```

This is necessary for https://github.com/electron/electron-typescript-definitions/issues/25.

**Comment by MarshallOfSound** [comment]
https://github.com/electron/electron-typescript-definitions/blob/master/lib/utils.js#L128-L132

**Comment by miniak** [comment]
Well, there is a reason why things need to be specified as optional. I don't think it's a good pattern to do it the other way around.

**Comment by MarshallOfSound** [comment]
@miniak I was linking that for future reference, do you disagree with that comment?  If so do you think the default for that function should be returning false?

**Comment by MarshallOfSound** [comment]
Fixed in `next`
