### ISSUE TITLE
Cleanup RendererInterface

### ISSUE THREAD

**Issue by miniak** [electron/typescript-definitions#31]
`import { webviewTag } from 'electron'` in the renderer context does not make sense.

I would also suggest renaming the `WebviewTag` interface to `WebViewElement` to make it more consistent with other `HTMLElement` subclasses.

**Comment by MarshallOfSound** [comment]
This was implemented a while back with the `electron/renderer`, `electron/common` and `electron/browser` import aliases.

i.e. for process-specific type safety you can do this

```js
import { webviewTag } from 'electron/renderer';
```
