### ISSUE TITLE
Cleanup MainInterface

### ISSUE THREAD

**Issue by miniak** [electron/typescript-definitions#34]
These modules are not directly available in the main process:

- `ClientRequest`
- `Cookies`
- `Debugger`
- `DownloadItem`
- `IncomingMessage`
- `TouchBar`
- `WebRequest`

They should not be listed in `MainInterface` and/or `AllElectron`

**Comment by MarshallOfSound** [comment]
Fixed in b4d9d133cccd0f712d681217703195769ea7a639
