### ISSUE TITLE
Empty Object should not become any

### ISSUE THREAD

**Issue by miniak** [electron/typescript-definitions#35]
For example, the `userInfo` argument of `continue-activity` on `App` is declared as `Object` in API docs. However it's generated as `any` instead of `Object`.

Other examples:
- `continue-activity` event - `userInfo`
- `ready` event - `launchInfo`
- `app.setUserActivity` method - `userInfo`
- `autoUpdater.setFeedURL` method - `requestHeaders`

**Comment by MarshallOfSound** [comment]
@miniak Unless the structure of the object is explicitly declared the safest thing we can is declare the type as `any`

**Comment by miniak** [comment]
@MarshallOfSound well, I don't agreee with that. Declaring it as generic Object is better, otherwise you can pass a primitive type, which is not an object.

**Comment by MarshallOfSound** [comment]
Simple fix if you want to change it 👍 

https://github.com/electron/electron-typescript-definitions/blob/master/lib/utils.js#L68
