### ISSUE TITLE
suggestion: additional instance properties on MenuItem from constructor options

### ISSUE THREAD

**Issue by shiftkey** [electron/typescript-definitions#46]
The full list of options in [`MenuItemConstructorOptions`](https://electron.atom.io/docs/api/menu-item/#new-menuitemoptions) isn't then reflected in the available [instance properties](https://electron.atom.io/docs/api/menu-item/#instance-properties) when you want to inspect the created `MenuItem`.

An incomplete list of additional properties that can be added - these can be all marked as `readonly` to make it clear these shouldn't be mutated, but I'm happy to defer to the team on what we should be displayed here.

```ts
interface MenuItem {
  readonly accelerator?: Electron.Accelerator
  readonly submenu?: Electron.Menu
  readonly role?: string
  readonly type: 'normal' | 'separator' | 'submenu' | 'checkbox' | 'radio'
}
```

**Comment by MarshallOfSound** [comment]
@shiftkey The issue here is semantically declaring readonly properties in a parseable way in the markdown docs, and then parsing that in the docs linter.  Once that is figured out adding those props here is easy 👍

**Comment by jonolo6** [comment]
I'm working on moving my electron app that uses Mobx and React onto Typescript. 

Any idea how to get around the following error?

> TS2339: Property 'submenu' does not exist on type 'MenuItem'.

Here's my code: 

`
@inject('userStore') @observer
class LoggedInMenuCoordinater extends Component<any, any>{
    logOutMenu: any;

    constructor(props: {}){
        super(props)

        const {Menu} = require('electron').remote
        this.logOutMenu = Menu.getApplicationMenu().items[0].submenu.items[8]
    }

    render():  null {
        if (this.props.userStore.isLoggedIn) {
            this.logOutMenu.enabled = true
        } else {
            this.logOutMenu.enabled = false
        }

        return null;
    }
}
`

**Comment by jonolo6** [comment]
Resolved it temporarily. Not pretty!

```js
@inject('userStore') @observer
class LoggedInMenuCoordinater extends Component<any, any>{
    logOutMenu: Electron.MenuItem;

    constructor(props: {}){
        super(props)

        const {Menu} = require('electron').remote
        const firstMenu = Menu.getApplicationMenu().items[0] as Electron.MenuItemConstructorOptions;
        this.logOutMenu = (firstMenu.submenu as Electron.Menu).items[8]
    }

    render():  null {
        if (this.props.userStore.isLoggedIn) {
            this.logOutMenu.enabled = true
        } else {
            this.logOutMenu.enabled = false
        }

        return null;
    }
}
```

**Comment by Paxa** [comment]
Docs don't have `submenu` property but actual object has it.
I guess we should update docs and ts definitions

**Comment by MarshallOfSound** [comment]
This is done / fixed in the docs so I'm going to close this out
