### ISSUE TITLE
SystemPreferences.getUserDefault returns void

### ISSUE THREAD

**Issue by shiftkey** [electron/typescript-definitions#58]
The current declaration for [systemPreferences.getUserDefault](https://electron.atom.io/docs/api/system-preferences/#systempreferencesgetuserdefaultkey-type-macos) for this method looks like this:

```ts
    /**
     * Get the value of key in system preferences. This API uses NSUserDefaults on
     * macOS. Some popular key and types are:
     */
    getUserDefault(key: string, type: 'string' | 'boolean' | 'integer' | 'float' | 'double' | 'url' | 'array' | 'dictionary'): void;
```

To be compatible with the flexible `type` that a user can specify, it should return `any` instead of `void`.

**Comment by shiftkey** [comment]
Actually, the common settings could be provided as overloads to help make this API more easier to navigate:

```ts
getUserDefault(key: 'AppleInterfaceStyle', type: 'string'): string;
getUserDefault(key: 'AppleAquaColorVariant', type: 'number'): number;
...
```

**Comment by MarshallOfSound** [comment]
@shiftkey The second thing isn't possible AFAIK with our current parsing tech, setting the type to `any` though is pretty straight forward
