### ISSUE TITLE
Several links are broken in type docs

### ISSUE THREAD

**Issue by Tyriar** [electron/typescript-definitions#83]
Looks like HTML text content is getting stripped out with the tags or something.

AppDetailsOptions

![image](https://user-images.githubusercontent.com/2193314/32977679-3626a50c-cbe7-11e7-8979-483fa88006ca.png)

BrowserWindowConstructorOptions

![image](https://user-images.githubusercontent.com/2193314/32977686-506e278c-cbe7-11e7-9468-910e43039d97.png)

**Comment by MarshallOfSound** [comment]
@tyriar This content will be stripped out in the docs linter

**Comment by MarshallOfSound** [comment]
Fixed in `next`
