### ISSUE TITLE
Listener callbacks of type 'Function' don't work well with --noImplicitAny

### ISSUE THREAD

**Issue by tao-cumplido** [electron/typescript-definitions#88]
For example in BrowserWindow there is this definition:
```typescript
on(event: 'closed', listener: Function): this;
```
With `--noImplictAny` on and `--strictNullChecks` off the following results in `TS7011: Function expression, which lacks return-type annotation, implicitly has an 'any' return type.`
```typescript
window.on('closed', () => window = null);
```
This is because TypeScript infers `null` as `any` without `--strictNullChecks`.
When `Function` is replaced with `() => void` it works.

**Comment by MarshallOfSound** [comment]
Fixed in `next`
